export const ACTION_TYPES = `complete_task skip_task delete_task create_task update_task create_goal update_goal update_goal_progress archive_goal delete_goal create_habit update_habit delete_habit toggle_habit create_note update_note delete_note add_inbox update_inbox delete_inbox create_workspace_page update_workspace_page set_workspace_page_lock set_workspace_page_verified archive_workspace_page restore_workspace_page delete_workspace_page create_workspace_space update_workspace_space delete_workspace_space create_workspace_database update_workspace_database delete_workspace_database create_workspace_canvas add_workspace_canvas_node delete_workspace_canvas create_workspace_record update_workspace_record delete_workspace_record create_workspace_project update_workspace_project delete_workspace_project link_task_project set_task_dependencies create_workspace_automation run_workspace_automation delete_workspace_automation create_workspace_meeting update_workspace_meeting delete_workspace_meeting meeting_actions_to_tasks create_scheduling_link update_scheduling_link delete_scheduling_link create_smart_meeting update_smart_meeting schedule_smart_meeting delete_smart_meeting create_workspace_form update_workspace_form delete_workspace_form add_workspace_property update_workspace_property delete_workspace_property auto_schedule_project schedule_habit_blocks autopilot_week protect_weekly_focus build_workspace_agenda create_daily_note save_search update_saved_search delete_saved_search import_workspace_markdown create_clip update_clip delete_clip clip_to_page add_page_comment resolve_page_comment delete_page_comment restore_page_version create_workspace_site update_workspace_site delete_workspace_site start_time_tracking stop_time_tracking delete_time_entry create_custom_agent update_custom_agent run_custom_agent delete_custom_agent set_setting set_profile select_date set_tab open_quick_add set_timeline_layout compress_day compress_week buffer_guard auto_lock focus_shield recovery_buffers conflict_sweep energy_fit overload_guard context_batching travel_buffer focus_budget meeting_defrag momentum_chain deadline_backplan habit_rescue no_meeting_guard deep_work_reserve context_switch_shield`.split(" ");

export const SETTING_KEYS = `experienceMode globalMemoryEnabled coachMode accountability language theme accentTheme customAccentEnabled customAccentHue customAccentSaturation customAccentLightness canvasTheme visualEnergy fontScale fontDesign notificationsEnabled taskReminders eveningReview eveningReviewTime morningPlanningReminder morningPlanningTime overdueReminder quietHoursStart quietHoursEnd safeMode autoLearn aiAssistantMode studyExplanationLevel studyInteractiveSteps studyVisualizations studyCheckYourself calendarSyncEnabled healthSyncEnabled healthPlanningEnabled iCloudSyncEnabled cloudSyncEnabled timelineShowDayPath timelineSmartDensity timelineRealityEnabled timelineGravityEnabled timelineBufferGuardEnabled timelineAutoLockEnabled timelineDeadlineRadarEnabled timelineRecoveryBuffersEnabled timelineConflictSweepEnabled timelineEnergyFitEnabled timelineOverloadGuardEnabled timelineContextBatchingEnabled timelineTravelBufferEnabled timelineFocusBudgetEnabled timelineMeetingDefragEnabled timelineMomentumChainEnabled timelineDeadlineBackplanEnabled timelineHabitRescueEnabled timelineNoMeetingGuardEnabled timelineDeepWorkReserveEnabled timelineContextSwitchShieldEnabled timelineAutoCompleteElapsedTasks timelineSuggestionsEnabled timelineLayout weekTimelineLayout timePolicy.weeklyFocusGoalMinutes timePolicy.minimumFocusBlockMinutes timePolicy.preferredFocusBlockMinutes timePolicy.breakMinutes timePolicy.workHoursStart timePolicy.workHoursEnd timePolicy.meetingHoursStart timePolicy.meetingHoursEnd timePolicy.autoScheduleBreaks timePolicy.protectPersonalTime timePolicy.noMeetingWeekdays`.split(" ");

export const PROFILE_KEYS = `name nickname category primaryGoal goalWhy struggle fixedCommitments currentHabits productiveHours planningPreferences selfDescription wakeTime sleepTime chronotype discipline bodyRhythmEnabled cycleStartDate cycleLengthDays cyclePeriodDays`.split(" ");
const CATEGORIES = ["focus", "work", "study", "fitness", "life", "rest"];
const actionSchema = { type: "object", additionalProperties: false, required: ["type"], properties: { type: { type: "string", enum: ACTION_TYPES }, taskId: { type: "string" }, itemId: { type: "string" }, title: { type: "string" }, body: { type: "string" }, date: { type: "string" }, startTime: { type: "string" }, durationMinutes: { type: "integer", minimum: 0, maximum: 480 }, category: { type: "string", enum: CATEGORIES }, key: { type: "string" }, value: { type: "string" }, boolValue: { type: "boolean" }, intValue: { type: "integer", minimum: -1440, maximum: 10000 }, tags: { type: "array", maxItems: 20, items: { type: "string" } } } };

export const schemas                          = {
  coach: { type: "object", additionalProperties: false, required: ["reply", "memories", "actions"], properties: { reply: { type: "string" }, memories: { type: "array", maxItems: 3, items: { type: "object", additionalProperties: false, required: ["category", "fact", "confidence"], properties: { category: { type: "string", enum: ["goal", "routine", "blocker", "preference", "pattern"] }, fact: { type: "string" }, confidence: { type: "number", minimum: 0, maximum: 1 } } } }, actions: { type: "array", maxItems: 40, items: actionSchema } } },
  plan: { type: "object", additionalProperties: false, required: ["title", "intention", "planScore", "coachNote", "tasks"], properties: { title: { type: "string" }, intention: { type: "string" }, planScore: { type: "integer", minimum: 0, maximum: 100 }, coachNote: { type: "string" }, tasks: { type: "array", minItems: 1, maxItems: 16, items: { type: "object", additionalProperties: false, required: ["title", "note", "startTime", "endTime", "durationMinutes", "section", "category", "priority", "mustWin"], properties: { title: { type: "string" }, note: { type: "string" }, startTime: { type: "string" }, endTime: { type: "string" }, durationMinutes: { type: "integer", minimum: 5, maximum: 480 }, section: { type: "string", enum: ["morning", "day", "evening", "night"] }, category: { type: "string", enum: CATEGORIES }, priority: { type: "integer", minimum: 1, maximum: 3 }, mustWin: { type: "boolean" } } } } } },
  profile: { type: "object", additionalProperties: false, required: ["summary", "planningRules", "risks", "suggestedHabits"], properties: { summary: { type: "string" }, planningRules: { type: "array", minItems: 2, maxItems: 6, items: { type: "string" } }, risks: { type: "array", minItems: 1, maxItems: 5, items: { type: "string" } }, suggestedHabits: { type: "array", maxItems: 4, items: { type: "string" } } } },
  horizon: { type: "object", additionalProperties: false, required: ["title", "summary", "checkpoints"], properties: { title: { type: "string" }, summary: { type: "string" }, checkpoints: { type: "array", minItems: 2, maxItems: 12, items: { type: "object", additionalProperties: false, required: ["label", "outcome", "actions"], properties: { label: { type: "string" }, outcome: { type: "string" }, actions: { type: "array", minItems: 1, maxItems: 5, items: { type: "string" } } } } } } },
  subtasks: { type: "object", additionalProperties: false, required: ["subtasks"], properties: { subtasks: { type: "array", minItems: 2, maxItems: 7, items: { type: "string" } } } }
};
